### ISSUE TITLE
Need to add external font file

### ISSUE THREAD

**Issue by ziauddin-sayyed** [Vincenius/static-website-template#10]
Thanks in advance,

Please help me out in adding font faces and aboutus page.

**Comment by EtienneDx** [comment]
I've recently come into this issue too, and solved it by adding the following to my webpack.config.js : 

```js
module.exports = {
  // ...
  module: {
    rules: [
      // ...
      {
        test: /\.woff2?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        // Limiting the size of the woff fonts breaks font-awesome ONLY for the extract text plugin
        // loader: "url?limit=10000"
        use: "url-loader",
      },
      {
        test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/,
        loader: 'file-loader',
        options: {
          name: 'font/[name].[ext]',
        },
      },
    ]
  }
  // ...
}
```

This will move your fonts either inside of the js bundle or in a `font` directory in the `dist` folder.

To use it, you need to add 2 dependencies tho:

`npm i -D url-loader file-loader`

PS: This will only export fonts which are imported via the js (I used this with a css-loader to import fonts and css from the node-modules into the dist). This might not solve everything but if it can help it's still a good thing done :)

**Comment by Vincenius** [comment]
As there were not more questions here I'll close this issue - thanks @EtienneDx for your support
