### ISSUE TITLE
Trying to remove Sass and only use Tailwind

### ISSUE THREAD

**Issue by eduardonwa** [Vincenius/static-website-template#22]
I don't use Sass but I do use Tailwind, any tips on how to go about this? For the most part everything installed seems useful to me, especially the posthtml-modules plug-in I come from a Laravel environment and that looks familiar to me, it's also one of the reasons why I want this to work so much. Just uninstall scss with npm but what other thing would need to be deactivated? I tried to follow along with the blog post but i think it's been a while since this and I think something came up in the process. 

If i run ```npm install``` it says i need to have node-sass installed, once i get that installed everything works as you intended but i don't use sass i know it's great tool and all. Thanks.

**Comment by Vincenius** [comment]
Hi Eduardo :) I've never used Tailwind so I'm not 100% sure. But if you use only Tailwind I think you can remove all CSS related scripts from the package.json and uninstall `node-sass`, `postcss-cli`, `stylelint`, and `autoprefixer`

If you also want to create custom CSS next to Tailwind you can keep everything as it is and use sass along with Tailwind - it should also work together

**Comment by eduardonwa** [comment]
Thanks
